### ISSUE TITLE
deviceType is undefined in case of opener

### ISSUE THREAD

**Issue by stefanerdmann** [smaragdschlange/ioBroker.nuki#30]
Hi,

I am using the following setup:

NUKI BRIDGE
NUKI OPENER
NUKI LOCK

All devices are recognised by your adapter and objects are created. But when I am pressing the open button of the opener nothing happens and the log says: null. As it seemed like your adapter does not get the correct device type (which should be the value 2) for the opener I added a log statement in your code and it turns out that the deviceType is 'undefined' for the opener.  In the object browser I can also see that there is no name (the name next to the id) for the opener but for the other two devices. Seems like your adapter has trouble to receive the correct information for the opener.

This is were I added the log statement.

`function getLockState(_nukiId) {
    var deviceType = adapter.getState(adapter.name+'.'+adapter.instance+'.'+_nukiId+'.info.deviceType', function (err, state) { return state.val; });
    var lockStateUrl = null;`

**Comment by smaragdschlange** [comment]
Hi,
thanks for the analysis. I'll try to fix it, but I don't own an opener, so it could take some turns.

**Comment by smaragdschlange** [comment]
Hi there,
could you please install version 1.1.3 here from GitHub and test? As I wrote before I don't own an Opener...

Thanks!

Regards, Sven

**Comment by stefanerdmann** [comment]
I installed version 1.1.3 and i get the following errors in the log:


> host.raspberrypi | 2020-02-24 13:24:53.315 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
> -- | -- | -- | --
> host.raspberrypi | 2020-02-24 13:24:53.314 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
> host.raspberrypi | 2020-02-24 13:24:53.314 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
> host.raspberrypi | 2020-02-24 13:24:53.314 | error | Caught by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
> host.raspberrypi | 2020-02-24 13:24:53.314 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
> host.raspberrypi | 2020-02-24 13:24:53.313 | error | Caught by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
> host.raspberrypi | 2020-02-24 13:24:53.313 | error | Caught by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.nuki/main.js:1026:21)
> host.raspberrypi | 2020-02-24 13:24:53.313 | error | Caught by controller[0]: at updateAllLockStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:776:13)
> host.raspberrypi | 2020-02-24 13:24:53.313 | error | Caught by controller[0]: at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:323:13)
> host.raspberrypi | 2020-02-24 13:24:53.312 | error | Caught by controller[0]: at initNukiOpenerStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:648:29)
> host.raspberrypi | 2020-02-24 13:24:53.311 | error | Caught by controller[0]: ReferenceError: _obj is not defined
> 



nuki.0 | 2020-02-24 13:25:33.266 | error | (2371) ReferenceError: _obj is not defined at initNukiOpenerStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:648:29) at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/m
-- | -- | -- | --
nuki.0 | 2020-02-24 13:25:33.265 | error | (2371) uncaught exception: _obj is not defined

**Comment by smaragdschlange** [comment]
Oh, sorry, it's been late last night and I wasn't able to test properly. I fixed the _obj issue. Please install again from GitHub.

Thanks.
Sven

**Comment by stefanerdmann** [comment]
now it connects successfully, but I still get an error when clicking the open button:

nuki.0 | 2020-02-24 16:00:46.850 | error | (6202) null

The name of the opener and the deviceType is now set correctly (at least the values in the object tree)

**Comment by smaragdschlange** [comment]
Ok, I've found the issue and fixed it - finally. There were actually two problems: the error null message was caused by the bridge beeing called two times in a very short period of time. And the deviceType undefined issue was caused by the asynchronous nature of state calls in the adapter. 
Please reinstall the current GutHub version of the adapter and check.

Thank you.
Sven
